version: '3'

services:
  webshop:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}webshop
    ports:
      - "8080:8080"
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webshop
      MYSQL_PASSWORD: dockers
    ports:
      - "3306:3306"