version: '3'

services:
  webshop:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}webshop
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
      - rabbitmq
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webshop
      MYSQL_PASSWORD: dockers
    ports:
      - "3306:3306"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672" 